name: Build and release for macOS

on:
  push:
    branches:
      - main

jobs:
  check_version:
    uses: ./.github/workflows/check-version-tag.yml
  build:
    needs: [check_version]
    if: ${{ needs.check_version.outputs.should_run != 'false' }}
    runs-on: ${{ matrix.runner }}
    name: Build Mac ${{ matrix.arch }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: x86_64
            runner: macro-x641
          - arch: arm64
            runner: macro-arm1
    steps:
      - name: Turn off line ending conversion in git
        run: |
          cd ${{ inputs.working_dir }}
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch and build
        run: |
          cd libreoffice-core
          ./autogen.sh --with-distro=LOKit-Mac --with-external-tar="$RUNNER_TOOL_CACHE/lokit-external"
          make build
          tar -cJf ../libreofficekit-mac-${{ matrix.arch }}.tar.xz instdir
          cd ..
          shasum -a 256 libreofficekit-mac-${{ matrix.arch }}.tar.xz > libreofficekit-mac-${{ matrix.arch }}.tar.xz.sha256sum
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libreofficekit-mac-${{ matrix.arch }}.tar.xz,libreofficekit-mac-${{ matrix.arch }}.tar.xz.sha256sum"
          allowUpdates: true
          artifactErrorsFailBuild: true
          name: ${{ needs.check_version.outputs.version }}
          tag: ${{ needs.check_version.outputs.version }}
          body: |
            This is an automated release built from the `main` branch.
            For changes, please review the commit log.
